unisoc/zephyr

drivers/interrupt_controller/CMakeLists.txt

ipi add include header
Signed-off-by: yuanjiang.li <yuanjiang.li@unisoc.com>

drivers: interrupt_controller: for ipc interface

---

drivers/wifi/Kconfig

Add WIFI_STA_NAME and WIFI_AP_NAME for generic use of Wi-Fi driver.

drivers: wifi: Add new generic configuration

---

drivers/wifi/uwp/Kconfig.uwp
drivers/wifi/uwp/wifi_cmdevt.c
drivers/wifi/uwp/wifi_cmdevt.h
drivers/wifi/uwp/wifi_ipc.c
drivers/wifi/uwp/wifi_main.c
drivers/wifi/uwp/wifi_main.h
drivers/wifi/uwp/wifi_txrx.c
drivers/wifi/uwp/wifi_txrx.h

Recycle rx buffer if not needed
and match the lastest cmd from wifimgr_drv.h.

drivers: wifi: Recycle rx buffer and update Wi-Fi command

---

include/arch/arm/cortex_m/scripts/linker.ld
include/linker/linker-defs.h
include/toolchain/gcc.h
kernel/init.c

__ramfunc is an intrinsis of IAR, using this places a function in RAM
instead of Flash. Code that for example reprograms flash at runtime
can't execute from flash, in that case must placing code into flash.
This commit create a new section named '.ramfunc' in link scripts,
all functions has __ramfunc keyword saved in thats sections and
will load from flash to sram after the system booted.
Signed-off-by: qianfan Zhao <qianfanguijin@163.com>

arm: Placing the functions which holds __ramfunc into '.ramfunc'

---

drivers/wifi/uwp/Kconfig.uwp
drivers/wifi/uwp/wifi_main.c

Remove sram initialization from driver.

drivers: wifi: Remove sram initialization

---

drivers/wifi/uwp/wifi_main.c

To use ethernet arp, add ethernet_init invoked.

drivers: wifi: Add ethernet_init in init_fn

---

subsys/wifi/cmd_prcs.c

Tentative fix for LOG macro. But there's still error
when enabling NET_LOG macro.

subsys: wifi: Tentative fix compile error for LOG macro

---

drivers/wifi/uwp/wifi_cmdevt.c
drivers/wifi/uwp/wifi_ipc.c
drivers/wifi/uwp/wifi_main.c
drivers/wifi/uwp/wifi_main.h
drivers/wifi/uwp/wifi_txrx.c

Add semicolon at end of LOG_MODULE_REGISTER/
DELCARE macro.

drivers: wifi: Minor modification for logger

---

soc/arm/unisoc_uwp/uwp566x/soc.c

soc: arm: del uwp_cache_init api.

soc: arm: Add uwp_cache_init api.

---

drivers/wifi/uwp/wifi_cmdevt.c
drivers/wifi/uwp/wifi_main.c

1. Remove ethernet_init from softap iface init.
2. Add disconnect_cb invoked when disconnect happens.
3. Use softap callback of softap iface.

drivers: wifi: Fix cmdevt issues

---

drivers/wifi/uwp/wifi_cmdevt.c

Return 0 if wifimgr invoked it.

drivers: wifi: Drop stop_ap cmd to CP

---

subsys/wifi/CMakeLists.txt
subsys/wifi/Kconfig
subsys/wifi/ap.c
subsys/wifi/cmd_prcs.c
subsys/wifi/dhcpc.c
subsys/wifi/evt_lsnr.c
subsys/wifi/led.c
subsys/wifi/led.h
subsys/wifi/wifimgr.c
subsys/wifi/wifimgr.h

Use generic LED interace instead of GPIO.

subsys: wifi: refactor led part of WiFi manager

---

include/net/wifimgr_drv.h

This patch is to add new driver api for wifi hardware test.
Signed-off-by: Jessie.Xin <Jessie.Xin@unisoc.com>

include: net: add new wifi driver api for hw_test

---

subsys/wifi/ap.c
subsys/wifi/os_adapter.h
subsys/wifi/sm.c
subsys/wifi/sm.h
subsys/wifi/sta.c
subsys/wifi/wifimgr.h

Use workqueue to avoid the semaphore issue in POSIX timeout handling.

subsys: wifi: use workqueue to offload event timeout handling

---

include/net/wifimgr_drv.h

This patch is to fix build warning in wifi_drv_api.
Signed-off-by: Jessie.Xin <Jessie.Xin@unisoc.com>

include: net: fix build warning in wifi_drv_api

---

drivers/wifi/uwp/wifi_main.c

Should unref net_buf rather than net_pkt because it's sending
net_buf one by one as of now. We add this unref if data_len
exceeds maximum value and tx fails.

drivers: wifi: uwp: Unref net_buf if tx error happens

---

drivers/wifi/uwp/wifi_cmdevt.c

It's possible to connect to a specific AP via BSSID.

drivers: wifi: uwp: Connect to AP via BSSID

---

subsys/wifi/ap.c
subsys/wifi/api.c
subsys/wifi/api.h
subsys/wifi/cli.c
subsys/wifi/config.c
subsys/wifi/config.h
subsys/wifi/drv_iface.c
subsys/wifi/drv_iface.h
subsys/wifi/sta.c
subsys/wifi/wifimgr.h

- Use settings_str_from_bytes/settings_bytes_from_str
to handle MAC address.
- Add params check for set_conf
- Add autorun to config.

subsys: wifi: refactor config and add params check for set_conf

---

drivers/wifi/uwp/wifi_cmdevt.c
drivers/wifi/uwp/wifi_main.c
drivers/wifi/uwp/wifi_txrx.c

One semaphore triggers to read all data in rx thread,
in case that there is data left.

drivers: wifi: uwp: Read all data in rx thread

---

subsys/wifi/CMakeLists.txt
subsys/wifi/Kconfig
subsys/wifi/api.c
subsys/wifi/autorun.c
subsys/wifi/cli.c
subsys/wifi/config.h
subsys/wifi/drv_iface.c
subsys/wifi/evt_lsnr.c
subsys/wifi/led.c
subsys/wifi/led.h
subsys/wifi/os_adapter.h
subsys/wifi/wifimgr.c

Add STA and AP related macros to enable
building each one separately.

subsys: wifi: add STA and AP related macros

---

drivers/wifi/uwp/wifi_cmdevt.c
drivers/wifi/uwp/wifi_main.c

1) Do not drop event callbacks.
2) Allow a command which already has corresponding callback.
2) Correct some typos.

drivers: wifi: uwp: Keep all event callbacks

---

subsys/wifi/autorun.c

subsys: wifi: fix autorun issue of AP

---

ext/hal/Kconfig
ext/hal/unisoc/CMakeLists.txt

The unisoc hal used to handle uwp series SoCs.
Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>

ext: hal: unisoc: Rename uwp5661 to uwp.

---

soc/arm/unisoc_uwp/uwp566x/Kconfig.defconfig.uwp5662

soc: uniso_uwp: set clock to 320M

---

subsys/wifi/CMakeLists.txt
subsys/wifi/Kconfig
subsys/wifi/ap.c
subsys/wifi/autorun.c
subsys/wifi/os_adapter.h
subsys/wifi/sm.c
subsys/wifi/sm.h
subsys/wifi/sta.c
subsys/wifi/timer.c
subsys/wifi/timer.h
subsys/wifi/wifimgr.c
subsys/wifi/wifimgr.h

Use dedicated workqueue for timeout and autorun.

subsys: wifi: use dedicated workqueue for timeout and autorun

---

drivers/wifi/uwp/wifi_cmdevt.c

Correct rtt event check if expected len equals input len.

drivers: wifi: uwp: Correct rtt event check

---

drivers/pinmux/pinmux_uwp.c

to strengthen code's readiability, change name of functions'parameter

change pinmux functions parameter's name

---

drivers/wifi/uwp/wifi_main.c

Drop retval check of wifi_rf_init and wifi_cmd_get_cp_info.
Two reasons:
1) There are already check inside them. It's easy to find if error happens.
2) Protect mulitple initializations from error
which might be tentative debug (parameters of get_cp_info cmd changed).
In this case, it should be allowed to go on because of nonfatal error.

drivers: wifi: uwp: Drop unnecessary returns

---

drivers/wifi/uwp/wifi_main.c
drivers/wifi/uwp/wifi_txrx.c
drivers/wifi/uwp/wifi_txrx.h
subsys/net/l2/ethernet/ethernet.c

-drivers: wifi: uwp: Make wifi driver work in Zephyr 1.14
Tentative fix on adding msdu and addr space in the front of
net buffer.
Adapt with new APIs.
-subsys: net: l2: ethernet: Tentative modification for Wi-Fi L2
Account for more space(msdu and addr).

Make UWP Wi-Fi driver work on Zephyr 1.14

---

drivers/wifi/uwp/CMakeLists.txt
drivers/wifi/uwp/Kconfig.uwp
drivers/wifi/uwp/wifi_main.c
drivers/wifi/uwp/wifi_mem.c
drivers/wifi/uwp/wifi_mem.h
drivers/wifi/uwp/wifi_txrx.c
drivers/wifi/uwp/wifi_txrx.h

This share memory between AP and CP would not be cached.
Note: We must confirm the TX/RX buffer count and tweak the ram space.
That is, to decrease Zephyr ram.
Signed-off-by: Bub Wei bub.wei@unisoc.com

drivers: wifi: uwp: Manage TX/RX share memory

---

drivers/wifi/uwp/Kconfig.uwp
drivers/wifi/uwp/wifi_txrx.c
dts/arm/unisoc/uwp5661.dtsi

1)dts: arm: unisoc: Decrease Zephyr ram
For TX/RX share buffer management in UNISOC code, decrease Zephyr ram from 832KB to 640KB.
2)drivers: wifi: uwp: Tweak TX/RX buf config
Tweak start address from 0x19FBFF to 0x1A0000.
Set limit for TX/RX count and buffer size.

Tweak ram space

---

drivers/wifi/uwp/wifi_main.c

Add macro define for wifi_irq_init, which only on UWP5661.

drivers: wifi: uwp: wifi_irq_init only on UWP5661

---

drivers/wifi/uwp/main.c

Remove net_pkt_unref in uwp_tx, because
-if sent failed, net_if_tx would do it
-if sent succeeded, ethernet_send would do it.
Logs show:
[00:01:10.140,000] <err> net_pkt: *** ERROR ***
pkt 0x00113c78 is freed already by uwp_tx():605 (ethernet_send():598)

drivers: wifi: uwp: Remove unnecessary net_pkt_unref

---

drivers/wifi/uwp/cmdevt.c

Get band by channel. And report it to up layer.
band 2.4G: 1 <= channel <= 14.
band 5G:   36 <= channel <= 165.

drivers: wifi: uwp: Support band in scan results

---

subsys/bluetooth/host/l2cap.c
subsys/bluetooth/host/l2cap_br.c

when peer send disconnect request to zephyr,  bt can not find corresponding channenl , becuase of two 
Clever ,zephyr find current channel base on tx cid not rx cid

fix zephyr classic/LE can not disconnect

---

dts/arm/unisoc/uwp5661.dtsi
dts/arm/unisoc/uwp5662.dtsi

Change the address description.
Warning (simple_bus_reg): /soc/watchdog@40001000:
simple-bus unit address format error, expected "40010000"

dts: arm: unisoc: Fix incorrect description of wdg

---

subsys/bluetooth/host/smp.c

0x0007 是调用br 的接口注册的， 使用LE 轮询查询0x0007 是查不到的， 因为支持secure connection , pairing rsp 中ct2 bit 必须为1， 并且支持绑定

fixed smp can not find 0x0007 smp fixed channel
