unisoc/zephyr

drivers/flash/flash_uwp.c, drivers/serial/uart_uwp.c, soc/arm/unisoc_uwp/uwp566x/soc.c
uart poll_in/out will return failure if there is no input/output data.
Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>
=> drivers: serial: Fixed uart read issue.

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_cmdevt.h, drivers/wifi/uwp/wifi_main.c, drivers/wifi/uwp/wifi_main.h
Improve npi_send and download_ini with uniform usage.
=> drivers: wifi: Update npi and ini cmd

drivers/wifi/Kconfig, drivers/wifi/uwp/wifi_main.c
Replace WIFI_STA_NAME with WIFI_STA_DRV_NAME,
and replace WIFI_AP_NAME with WIFI_AP_DRV_NAME.
=> drivers: wifi: Update generic configuration

drivers/wifi/uwp/wifi_main.c
Take use of new driver config name.
=> drivers: wifi: Modify Wi-Fi driver name

drivers/wifi/uwp/Kconfig.uwp, drivers/wifi/uwp/wifi_cmdevt.h, drivers/wifi/uwp/wifi_main.c, include/net/wifimgr_drv.h
include: net: Add struct ehternet_api
=> drivers: wifi: Adapt ethernet api

drivers/gpio/Kconfig.uwp, drivers/gpio/gpio_uwp.c
add gpio groups and modified Kconfig
=> drivers: gpio: expand gpio groups

drivers/led/uwp.c
=> drivers: led: Correct LED driver

drivers/wifi/uwp/wifi_main.c, drivers/wifi/uwp/wifi_txrx.c
=> drivers: wifi: Add check for TX/RX

drivers/gpio/gpio_uwp.c
=> drivers: gpio: add gpio code

drivers/gpio/gpio_uwp.c
=> driver: gpio: correct gpio code

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_ipc.c, drivers/wifi/uwp/wifi_main.c, drivers/wifi/uwp/wifi_txrx.c
Do modifications for logger usage.
=> drivers: wifi: Take use of logger

drivers/gpio/gpio_uwp.c
=> driver: gpio: enable irq

drivers/flash/flash_uwp.c
drivers:Code implementation to improve sfc freq to 104m in mcuboot.
=> drivers:Code implementation to improve sfc freq to 104m in mcuboot.

subsys/wifi/Kconfig, subsys/wifi/ap.c, subsys/wifi/api.c, subsys/wifi/cli.c, subsys/wifi/cmd_prcs.c, subsys/wifi/dhcpc.c, subsys/wifi/drv_iface.c, subsys/wifi/evt_lsnr.c, subsys/wifi/os_adapter.h, subsys/wifi/sm.c, subsys/wifi/sta.c, subsys/wifi/wifimgr.c
=> subsys: wifi: use new log mechanism

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_cmdevt.h, drivers/wifi/uwp/wifi_ipc.c, drivers/wifi/uwp/wifi_main.c, drivers/wifi/uwp/wifi_main.h, drivers/wifi/uwp/wifi_txrx.c, drivers/wifi/uwp/wifi_txrx.h
1) Add two of struct wifi_device in wifi_priv.
2) Add func to get wifi_device by device.
3) Initialize index 0 for sta wifi_device and
index 1 for ap wifi_device.
4) Update parts of return values.
=> drivers: wifi: Modify driver_data usage

drivers/led/Kconfig, drivers/led/Kconfig.uwp, drivers/led/uwp.c
=> drivers: led: add led3's pin and config

include/net/wifimgr_drv.h, subsys/wifi/drv_iface.c
=> subsys: wifi: amend connect API to add disconnect callback

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_main.c
Add disconnect cb in connect api for remote disconnect.
=> drivers: wifi: Fix disconnect event

drivers/pinmux/CMakeLists.txt, drivers/pinmux/Kconfig, drivers/pinmux/Kconfig.uwp, drivers/pinmux/pinmux_uwp.c
=> drivers: pinmux: driver pinmap implement

drivers/flash/flash_uwp.c
Code implements for read/erase/write flash on xip.
=> drivers: flash: Code implements for read/erase/write flash on xip.

drivers/gpio/gpio_uwp.c
Fixed uwp gpio build issue.
Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>
=> drivers: gpio: Fixed uwp gpio build issue.

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_cmdevt.h, drivers/wifi/uwp/wifi_main.c
1) Use net_if_get_device instead.
2) Fix connect event due to status.
3) Add hardware test function.
=> drivers: wifi: Implement hw_test api

subsys/wifi/ap.c, subsys/wifi/cmd_prcs.c, subsys/wifi/cmd_prcs.h, subsys/wifi/drv_iface.c, subsys/wifi/drv_iface.h, subsys/wifi/evt_lsnr.c, subsys/wifi/evt_lsnr.h, subsys/wifi/sm.c, subsys/wifi/sm.h, subsys/wifi/sta.c, subsys/wifi/wifimgr.c, subsys/wifi/wifimgr.h
- Refactor WiFi manager
- Rename some function names
=> subsys: wifi: improve WiFi manager

drivers/wifi/uwp/wifi_main.c
1) It's good to take L2 header length marco instead.
2) Unref pkt if tx data failed. This will protect from memory leak.
=> drivers: wifi: uwp: Fix tx data

subsys/wifi/CMakeLists.txt, subsys/wifi/Kconfig, subsys/wifi/ap.c, subsys/wifi/api.c, subsys/wifi/cli.c, subsys/wifi/config.c, subsys/wifi/config.h, subsys/wifi/sta.c, subsys/wifi/wifimgr.c, subsys/wifi/wifimgr.h
Add configuration saving & loading handling.
=> subsys: wifi: add configuration saving & loading handling

drivers/flash/flash_uwp.c, subsys/wifi/config.c
Convert capital to lowercase for flash api.
=> drivers: flash: Convert capital to lowercase for flash api.

drivers/gpio/gpio_uwp.c
=> driver: gpio: repair code

subsys/wifi/ap.c, subsys/wifi/api.c, subsys/wifi/cli.c, subsys/wifi/cmd_prcs.c, subsys/wifi/config.c, subsys/wifi/dhcpc.c, subsys/wifi/dhcpc.h, subsys/wifi/drv_iface.c, subsys/wifi/drv_iface.h, subsys/wifi/evt_lsnr.c, subsys/wifi/led.h, subsys/wifi/sm.c, subsys/wifi/sta.c, subsys/wifi/wifimgr.h
=> subsys: wifi: adjust coding style

drivers/flash/flash_uwp.c
fix the issue of probable crash for flash.
=> drivers: flash: fix the issue of probable crash for flash.

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_cmdevt.h, drivers/wifi/uwp/wifi_main.c
New delete station command added for softap.
And new get_station command added for sta.
=> drivers: wifi: uwp: Support del_sta and get_sta

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_cmdevt.h
We are going to set channel width on softap.
=> drivers: wifi: uwp: Support channel width on start_ap

subsys/wifi/ap.c, subsys/wifi/api.c, subsys/wifi/cli.c, subsys/wifi/cmd_prcs.c, subsys/wifi/cmd_prcs.h, subsys/wifi/config.c, subsys/wifi/evt_lsnr.c, subsys/wifi/evt_lsnr.h, subsys/wifi/sm.c, subsys/wifi/sm.h, subsys/wifi/sta.c, subsys/wifi/wifimgr.c
Fix coding style issue reported by checkpatch.pl.
=> subsys: wifi: fix coding style issue reported by checkpatch.pl

subsys/wifi/api.c, subsys/wifi/cli.c, subsys/wifi/cmd_prcs.c, subsys/wifi/evt_lsnr.c, subsys/wifi/os_adapter.h
=> subsys: wifi: fix set_conf issue

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_main.c, include/net/wifimgr_api.h, include/net/wifimgr_drv.h, subsys/wifi/CMakeLists.txt, subsys/wifi/Kconfig, subsys/wifi/ap.c, subsys/wifi/api.c, subsys/wifi/api.h, subsys/wifi/cli.c, subsys/wifi/cmd_prcs.c, subsys/wifi/cmd_prcs.h, subsys/wifi/config.h, subsys/wifi/dhcpc.c, subsys/wifi/dhcpc.h, subsys/wifi/drv_iface.c, subsys/wifi/drv_iface.h, subsys/wifi/evt_lsnr.h, subsys/wifi/os_adapter.h, subsys/wifi/sm.h, subsys/wifi/sta.c, subsys/wifi/wifimgr.c, subsys/wifi/wifimgr.h
Refactor WiFi manager header files
=> Refactor WiFi manager header files

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_cmdevt.h, drivers/wifi/uwp/wifi_main.c, drivers/wifi/uwp/wifi_main.h
1)Implement get_capa on softap.
2)Change rssi type to signed char.
3)Change passphrase to psk for later use.
4)Update structure of get_station and get_cp_info
and use them in their commands.
=> drivers: wifi: uwp: Add/Update commands and events

subsys/wifi/ap.c, subsys/wifi/drv_iface.c, subsys/wifi/sm.c, subsys/wifi/sta.c
- Fix blacklist.
- Display security type of AP.
=> subsys: wifi: fix blacklist

drivers/wifi/uwp/wifi_txrx.c
1) Divide txrx_thread into rx_cmdevt_thread and rx_data_thread.
2) Make rx pkt/buf allocating wait forever.
3) Take rx iface by fixed sta one. Will fix later.
=> drivers: wifi: uwp: Refacotr txrx thread

boards/arm/96b_ivy5661/board.cmake, boards/arm/96b_ivy5661/support/openocd.cfg
Add OpenOCD support.
Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>
=> board: arm: 96b_viy5661: Add OpenOCD support.

subsys/wifi/ap.c, subsys/wifi/api.c, subsys/wifi/autorun.c, subsys/wifi/cli.c, subsys/wifi/sta.c
=> subsys: wifi: improve print message

subsys/wifi/autorun.c, subsys/wifi/cli.c
- Add params checking for wifimgr cli.
- Adjust coding style.
=> subsys: wifi: add params checking for wifimgr cli

subsys/wifi/ap.c, subsys/wifi/autorun.c, subsys/wifi/sta.c
Fix pointer issue of callbacks.
=> subsys: wifi: fix pointer issue of callbacks

subsys/wifi/autorun.c
=> subsys: wifi: adjust log for autorun

drivers/flash/flash_uwp.c
Signed-off-by: Stephen.Zhang <Stephen.Zhang@unisoc.com>
=> add cache_invalid after flash_write.

boards/arm/96b_ivy5661/96b_ivy5661.dts, subsys/settings/Kconfig, subsys/storage/flash_map/flash_map_default.c
-modify the flash dts and flash map
-modify setting flash area to 6
Signed-off-by: frank.lee <frank.lee@unisoc.com>
=> board: 96b_ivy5661.dts:

drivers/wifi/uwp/wifi_cmdevt.c, drivers/wifi/uwp/wifi_cmdevt.h, drivers/wifi/uwp/wifi_main.c, drivers/wifi/uwp/wifi_main.h
Implement rtt cmd and evevt.
Pending on new wifimgr and firmware.
=> drivers: wifi: uwp: Support wifi rtt

drivers/serial/Kconfig.uwp, drivers/serial/uart_uwp.c
add CONFIG_UART1_UWP to control uart1
=> driver: serial: add CONFIG_UART1_UWP to control uart1

subsys/wifi/drv_iface.c, subsys/wifi/sta.c
=> subsys: wifi: fix RTT problem

subsys/wifi/autorun.c, subsys/wifi/wifimgr.c, subsys/wifi/wifimgr.h
=> subsys: wifi: modify autorun

drivers/watchdog/wdt_uwp.c
implement watchdog driver code
=> implement watchdog driver code

subsys/wifi/common/Kconfig, subsys/wifi/common/psk.c, subsys/wifi/include/os_adapter.h, subsys/wifi/sta/sta.c
=> subsys: wifi: some minor modification

subsys/wifi/shell/shell.c, subsys/wifi/sta/sta.c
Adapt to new shell command definition.
=> subsys: wifi: adapt to new shell command definition

drivers/wifi/uwp/wifi_main.c
Insert msdu frag into the front for pkt so that
it's easy to modify how many bytes we need.
=> drivers: wifi: uwp: Insert msdu header frag

drivers/wifi/uwp/wifi_txrx.c
Modify iface checking.
And make each rx data independent.
=> drivers: wifi: uwp: Modify rx_complete

boards/arm/ivy5662/ivy5662.dts, drivers/serial/uart_uwp.c, dts/arm/unisoc/uwp5661.dtsi, dts/arm/unisoc/uwp5662.dtsi
=> driver: uart: add uart1 for uwp5662

drivers/pinmux/pinmux_uwp.c
=> implement pinmux code

dts/arm/unisoc/uwp5661.dtsi, dts/arm/unisoc/uwp5662.dtsi
correct wdg's address in dts files
=> correct wdg's address in dts files

boards/arm/ivy5662/ivy5662.dts
Signed-off-by: Stephen.Zhang <Stephen.Zhang@unisoc.com>
[change_type ] bringup --> sprd_chip_support
[tag_product ] common
=> subsys: wifi: uwp: update ivy5662.dts to suit settings_1.14

subsys/wifi/common/Kconfig, subsys/wifi/common/config.c, subsys/wifi/shell/shell.c
=> wifi: improve shell message

drivers/gpio/gpio_uwp.c
=> change gpio's function name

drivers/wifi/uwp/cmdevt.c
=> drivers: wifi: uwp: Rename ssid_length

drivers/wifi/uwp/main.c
=> drivers: wifi: uwp: Rename wifi_rf*.h

subsys/wifi/common/config.c, subsys/wifi/include/config.h
Signed-off-by: Stephen.Zhang <Stephen.Zhang@unisoc.com>
=> subsys: wifi: uwp: refactor wifi conf code.

subsys/wifi/common/config.c, subsys/wifi/common/ctrl_iface.c, subsys/wifi/shell/shell.c
=> subsys: wifi: fix coding style of config.c

drivers/wifi/uwp/main.c
=> drivers: wifi: uwp: Add macro dependency

boards/arm/ivy5662/ivy5662.dts, drivers/serial/uart_uwp.c, dts/arm/unisoc/uwp5662.dtsi
this patch modify bandrate for uart1
=> driver: uart: develop for uart1

drivers/dma/dma_uwp.c
this patch develop for dma uart1 tx
=> driver: dma: develop for dma uart1 tx
